In [1]:
import numpy as np
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [2]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [4]:
#realmente esta vacío
np.empty(5)

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [6]:
#matriz de 2x2, de 3's
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [10]:
#si yo le pongo un string, todo me lo va a converir a string
#el array debe tener el mismo tipo de dato
a = np.array([1,2,7,4,'3'])
print(a)

['1' '2' '7' '4' '3']


In [12]:
np.array([1,3,5,3],dtype=np.float32)

array([1., 3., 5., 3.], dtype=float32)

In [14]:
#me crea un array, que empieza en 2, termina en 11 y brinca de 2 en 2
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [16]:
#siempre va a ser cuadrada
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
#mi matriz no es cuadrada, es la diferencia con identity
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [20]:
#si le pongo el 1 al final, la posición de mi primer 1 se recorre uno, o sea empieza en la posición 1
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
a = np.array([[5,10,5,25],[1,20,25,20]])
print(a)
print(np.append(a,[4,5,6]))


[[ 5 10  5 25]
 [ 1 20 25 20]]
[ 5 10  5 25  1 20 25 20  4  5  6]


In [35]:
print(np.delete(a,0))


[10  5 25  1 20 25 20]


In [36]:
print(np.sort(a))

[[ 5  5 10 25]
 [ 1 20 20 25]]


In [37]:
print(a.flatten())

[ 5 10  5 25  1 20 25 20]


In [38]:
#me ordena la primer columna
print(np.sort(a, axis=0))

[[ 1 10  5 20]
 [ 5 20 25 25]]


In [43]:
b = a.copy() 
print(a)
b[0,0] = 2
print('\n', a)

[[ 2 10  5 25]
 [ 1 20 25 20]]

 [[ 2 10  5 25]
 [ 1 20 25 20]]


In [46]:
print(a.ndim) #dimensiones de mi array

2


In [48]:
print(a.shape) #dos renglones, 4 elementos/columnas

(2, 4)


In [49]:
print(a.size) #8 elementos en total

8


In [52]:
a = np.array([1,3,2,5,6,2])
print(a)

[1 3 2 5 6 2]


In [54]:
b = a.reshape(2,3) #el reshape debe tener el mismo tamaño que el original
#reshape aqui es 2,3 = 6, es el mismo size que la a original
print(b)

[[1 3 2]
 [5 6 2]]


In [56]:
b = a.reshape(3,2)
print(b)

[[1 3]
 [2 5]
 [6 2]]


In [58]:
b = a.reshape(1,6)
print(b)

[[1 3 2 5 6 2]]


In [59]:
b = a.reshape(6,1)
print(b)

[[1]
 [3]
 [2]
 [5]
 [6]
 [2]]


In [60]:
c = np.array([5,7,6,2,8,5,4,9,3,5,7,6])
c.reshape(2,3,2)

array([[[5, 7],
        [6, 2],
        [8, 5]],

       [[4, 9],
        [3, 5],
        [7, 6]]])

In [61]:
c.reshape(12,1)

array([[5],
       [7],
       [6],
       [2],
       [8],
       [5],
       [4],
       [9],
       [3],
       [5],
       [7],
       [6]])

In [98]:
d = c.reshape(6,2)
print(d)

[[5 5]
 [5 5]
 [5 5]
 [4 9]
 [3 5]
 [7 6]]


In [99]:
#accesar
d[0,0]

5

In [100]:
#del renglon 0 y 1, traeme el elemento 0
d[0:2,0]

array([5, 5])

In [101]:
#de todos los renglones, regresa la columna 1
d[:,1]

array([5, 5, 5, 9, 5, 6])

In [102]:
e = c.reshape(2,3,2)
print(e)

[[[5 5]
  [5 5]
  [5 5]]

 [[4 9]
  [3 5]
  [7 6]]]


In [103]:
#de todo, regresame el primer elemento, de las primeras filas
e[:,0,0]

array([5, 4])

In [104]:
#de todas las matrices, regresame todos los elementos, de la primer fila
e[:,0,:]

array([[5, 5],
       [4, 9]])

In [105]:
e[:,:,0] #regresame toda la primer columna, de las 2 matrices

array([[5, 5, 5],
       [4, 3, 7]])

In [106]:
e[:,:,0].flatten()

array([5, 5, 5, 4, 3, 7])

In [117]:
print(d)
d =b.ravel()

[[9 9]
 [5 5]
 [5 5]
 [4 9]
 [3 5]
 [7 6]]


In [119]:
print('\n')
print(d.flatten())
d[0]=9



[9 3 2 5 6 2]


In [120]:
a = np.arange(10,20,2)
b = np.arange(5,10,1)

In [126]:
print('a = ',a)
print('b = ',b)
print('a + b =',a+b)
print('a - b =',a-b)
print('a / b =',a/b)
print('a * b =',a*b)

a =  [10 12 14 16 18]
b =  [5 6 7 8 9]
a + b = [15 18 21 24 27]
a - b = [5 6 7 8 9]
a / b = [2. 2. 2. 2. 2.]
a * b = [ 50  72  98 128 162]


In [127]:
np.dot(a,b) #producto punto

510

In [128]:
np.mean(a)

14.0

In [129]:
np.median(a)

14.0

In [130]:
np.std(a)

2.8284271247461903

In [131]:
#si sumo un escalar a una matriz, le suma a todos
a+3

array([13, 15, 17, 19, 21])

In [132]:
np.min(a)

10

In [133]:
np.max(a)

18

In [137]:
print(a)
np.where(a <=12, 'es chiquito', np.where(a <=15, 'mediano','grandee'))

[10 12 14 16 18]


array(['es chiquito', 'es chiquito', 'mediano', 'grandee', 'grandee'],
      dtype='<U11')

In [139]:
np.where((a<=15)&(a>11),'mediano','grande')

array(['grande', 'mediano', 'mediano', 'grande', 'grande'], dtype='<U7')