1. Import the NUMPY package under the name np.

In [3]:
import numpy as np

2. Print the NUMPY version and the configuration.


In [4]:
print(np.version.version)

1.18.5


Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
a = np.random.random((2,3,5))

4. Print a.

In [6]:
print(a)

[[[0.64492988 0.5455964  0.94127303 0.82236419 0.20295164]
  [0.88014714 0.92370032 0.09171788 0.63699742 0.38484643]
  [0.24273257 0.70606966 0.37305633 0.69331161 0.16189039]]

 [[0.04347948 0.13605696 0.98121924 0.48309817 0.30062172]
  [0.00500647 0.23139894 0.43959202 0.75985554 0.98666823]
  [0.87274441 0.7807905  0.83774333 0.46527685 0.09322175]]]


5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [7]:
b = np.random.random((5, 2, 3))

6. Print b.

In [8]:
print(b)

[[[0.25291589 0.69920507 0.7677517 ]
  [0.17152327 0.88673094 0.43988265]]

 [[0.33948334 0.50338347 0.73804363]
  [0.84250557 0.10044532 0.38016583]]

 [[0.23443425 0.06472388 0.882294  ]
  [0.98309753 0.76606622 0.39768486]]

 [[0.66146727 0.91766097 0.57282532]
  [0.92746867 0.77128531 0.23369347]]

 [[0.95608481 0.73495815 0.38026499]
  [0.60677279 0.46160937 0.64070316]]]


7. Do a and b have the same size? How do you prove that in Python code?

In [9]:
len(a.flatten())

30

In [10]:
len(b.flatten())

30

8. Are you able to add a and b? Why or why not?

In [11]:
#No, because the structure is not the same

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [12]:
c= a.reshape((2, 3, 5))

10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [13]:
d = a+c

11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
print(d)

[[[1.28985976 1.09119281 1.88254607 1.64472837 0.40590329]
  [1.76029428 1.84740065 0.18343577 1.27399484 0.76969285]
  [0.48546514 1.41213932 0.74611266 1.38662321 0.32378078]]

 [[0.08695896 0.27211392 1.96243848 0.96619634 0.60124344]
  [0.01001294 0.46279788 0.87918405 1.51971108 1.97333646]
  [1.74548881 1.561581   1.67548665 0.93055369 0.1864435 ]]]


12. Multiply a and c. Assign the result to e.

In [15]:
e = np.multiply(a, c)

In [16]:
print(e)

[[[4.15934553e-01 2.97675435e-01 8.85994925e-01 6.76282856e-01
   4.11893698e-02]
  [7.74658989e-01 8.53222288e-01 8.41217038e-03 4.05765714e-01
   1.48106772e-01]
  [5.89191003e-02 4.98534364e-01 1.39171026e-01 4.80680982e-01
   2.62084986e-02]]

 [[1.89046540e-03 1.85114960e-02 9.62791196e-01 2.33383840e-01
   9.03734172e-02]
  [2.50647403e-05 5.35454692e-02 1.93241148e-01 5.77380441e-01
   9.73514196e-01]
  [7.61682801e-01 6.09633807e-01 7.01813879e-01 2.16482543e-01
   8.69029430e-03]]]


13. Does e equal to a? Why or why not?

In [17]:
#No, because the product of a mult is diff than a sum

14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [18]:
d.max()

1.9733364597377694

In [19]:
d.min()

0.010012939686329103

15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [20]:
f = np.empty([2, 3, 5])
print(f)

[[[4.15934553e-01 2.97675435e-01 8.85994925e-01 6.76282856e-01
   4.11893698e-02]
  [7.74658989e-01 8.53222288e-01 8.41217038e-03 4.05765714e-01
   1.48106772e-01]
  [5.89191003e-02 4.98534364e-01 1.39171026e-01 4.80680982e-01
   2.62084986e-02]]

 [[1.89046540e-03 1.85114960e-02 9.62791196e-01 2.33383840e-01
   9.03734172e-02]
  [2.50647403e-05 5.35454692e-02 1.93241148e-01 5.77380441e-01
   9.73514196e-01]
  [7.61682801e-01 6.09633807e-01 7.01813879e-01 2.16482543e-01
   8.69029430e-03]]]


16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [21]:
d_mean=np.mean(d)
d_max= np.max(d)
d_min= np.min(d)

In [22]:
dd= d.flatten()
print(dd)

[1.28985976 1.09119281 1.88254607 1.64472837 0.40590329 1.76029428
 1.84740065 0.18343577 1.27399484 0.76969285 0.48546514 1.41213932
 0.74611266 1.38662321 0.32378078 0.08695896 0.27211392 1.96243848
 0.96619634 0.60124344 0.01001294 0.46279788 0.87918405 1.51971108
 1.97333646 1.74548881 1.561581   1.67548665 0.93055369 0.1864435 ]


In [26]:
def fil(x):
    if x == d_max:
        print(100)
    if x < d_max and x >d_mean:
        print(75)
    if x == d_mean:
        print(50)
    if x == d_min:
        print(0)
    elif x > d_min and x < d_mean:
        print(25)

appen= list(filter(fil, dd))
print(appen)

75
75
75
75
25
75
75
25
75
25
25
75
25
75
25
25
25
75
25
25
0
25
25
75
100
75
75
75
25
25
[]


In [54]:

f=np.where(d == d_max, 100, (np.where(d ==d_mean, 50, (np.where(d==d_min, 0, (np.where(d > d_mean, 75, 25)))))))



In [55]:
print(f)

[[[ 75  75  75  75  25]
  [ 75  75  25  75  25]
  [ 25  75  25  75  25]]

 [[ 25  25  75  25  25]
  [  0  25  25  75 100]
  [ 75  75  75  25  25]]]
