# Lab NUMPY 

In [1]:
#1. Import the NUMPY package under the name np.

In [2]:
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.

In [4]:
print(np.version.version)

1.20.1


In [5]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
import random 

In [17]:
a = np.random.random((2, 3, 5))

In [19]:
#4. Print a.

print(a)

[[[0.19357966 0.96386788 0.83767753 0.17429143 0.94375187]
  [0.23896758 0.70834803 0.72342246 0.09559907 0.71473264]
  [0.18645847 0.57052686 0.38319755 0.41734468 0.5269705 ]]

 [[0.3481047  0.00617404 0.71511027 0.77253944 0.01069346]
  [0.09473739 0.66144871 0.54129895 0.31475582 0.38926166]
  [0.8708761  0.44625505 0.06568236 0.96521681 0.88890265]]]


In [57]:
#5. Create a 5x3x2 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [58]:
b = np.ones((5,3,2))

In [59]:
#6. Print b.

print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [24]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [53]:
print(a.size == b.size)

True


In [43]:
#8. Are you able to add a and b? Why or why not?

In [44]:
  print(a+b)   ##No se pueden unir por la forma de sus shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [60]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".pose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [61]:
c = b.transpose()

In [62]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [63]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [65]:
d = a+c

In [67]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [73]:
print(a)
print(d)

[[[0.19357966 0.96386788 0.83767753 0.17429143 0.94375187]
  [0.23896758 0.70834803 0.72342246 0.09559907 0.71473264]
  [0.18645847 0.57052686 0.38319755 0.41734468 0.5269705 ]]

 [[0.3481047  0.00617404 0.71511027 0.77253944 0.01069346]
  [0.09473739 0.66144871 0.54129895 0.31475582 0.38926166]
  [0.8708761  0.44625505 0.06568236 0.96521681 0.88890265]]]
[[[1.19357966 1.96386788 1.83767753 1.17429143 1.94375187]
  [1.23896758 1.70834803 1.72342246 1.09559907 1.71473264]
  [1.18645847 1.57052686 1.38319755 1.41734468 1.5269705 ]]

 [[1.3481047  1.00617404 1.71511027 1.77253944 1.01069346]
  [1.09473739 1.66144871 1.54129895 1.31475582 1.38926166]
  [1.8708761  1.44625505 1.06568236 1.96521681 1.88890265]]]


In [68]:
#12. Multiply a and c. Assign the result to e.

In [69]:
e = a * c

In [70]:
print(e)

[[[0.19357966 0.96386788 0.83767753 0.17429143 0.94375187]
  [0.23896758 0.70834803 0.72342246 0.09559907 0.71473264]
  [0.18645847 0.57052686 0.38319755 0.41734468 0.5269705 ]]

 [[0.3481047  0.00617404 0.71511027 0.77253944 0.01069346]
  [0.09473739 0.66144871 0.54129895 0.31475582 0.38926166]
  [0.8708761  0.44625505 0.06568236 0.96521681 0.88890265]]]


In [71]:
#13. Does e equal to a? Why or why not?

In [74]:
print(e == a)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [76]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [79]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)


print(d_max)
print(d_min)
print(d_mean)

1.9652168071138152
1.0061740363570313
1.4923264533552056


In [80]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [87]:
f = np.empty((2,3,5))

In [88]:
f

array([[[1.19357966, 1.96386788, 1.83767753, 1.17429143, 1.94375187],
        [1.23896758, 1.70834803, 1.72342246, 1.09559907, 1.71473264],
        [1.18645847, 1.57052686, 1.38319755, 1.41734468, 1.5269705 ]],

       [[1.3481047 , 1.00617404, 1.71511027, 1.77253944, 1.01069346],
        [1.09473739, 1.66144871, 1.54129895, 1.31475582, 1.38926166],
        [1.8708761 , 1.44625505, 1.06568236, 1.96521681, 1.88890265]]])

In [89]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

"\n#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n"

In [81]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""




"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'