In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.19.2


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.ones((2,3,5))
a = np.random.rand(2,3,5)
a = np.random.randint(10, size=(2,3,5))

In [4]:
#4. Print a.
print(a)

[[[3 5 0 6 0]
  [5 5 1 8 8]
  [7 5 7 0 2]]

 [[7 7 8 2 6]
  [0 6 3 6 4]
  [8 8 1 3 7]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3,))

In [6]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size == b.size

True

In [8]:
#8. Are you able to add a and b? Why or why not?
a + b
#No se pueden agregar porque son de diferente forma.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [9]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [10]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c
print(d)

#Funciona porque tienen la misma forma.

[[[4. 6. 1. 7. 1.]
  [6. 6. 2. 9. 9.]
  [8. 6. 8. 1. 3.]]

 [[8. 8. 9. 3. 7.]
  [1. 7. 4. 7. 5.]
  [9. 9. 2. 4. 8.]]]


In [11]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
#Los valores de d son los mismos valores de a sumados 1

[[[3 5 0 6 0]
  [5 5 1 8 8]
  [7 5 7 0 2]]

 [[7 7 8 2 6]
  [0 6 3 6 4]
  [8 8 1 3 7]]]
[[[4. 6. 1. 7. 1.]
  [6. 6. 2. 9. 9.]
  [8. 6. 8. 1. 3.]]

 [[8. 8. 9. 3. 7.]
  [1. 7. 4. 7. 5.]
  [9. 9. 2. 4. 8.]]]


In [12]:
#12. Multiply a and c. Assign the result to e.
e = a*c
print(e)

[[[3. 5. 0. 6. 0.]
  [5. 5. 1. 8. 8.]
  [7. 5. 7. 0. 2.]]

 [[7. 7. 8. 2. 6.]
  [0. 6. 3. 6. 4.]
  [8. 8. 1. 3. 7.]]]


In [13]:
#13. Does e equal to a? Why or why not?
e == a
#Es igual porque multiplicamos todos los números de a * c. Como c eran puros 1, a no cambia.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [14]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

9.0
1.0
5.6


In [15]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty([2,3,5], dtype = int)
print(f)

[[[4613937818241073152 4617315517961601024                   0
   4618441417868443648                   0]
  [4617315517961601024 4617315517961601024 4607182418800017408
   4620693217682128896 4620693217682128896]
  [4619567317775286272 4617315517961601024 4619567317775286272
                     0 4611686018427387904]]

 [[4619567317775286272 4619567317775286272 4620693217682128896
   4611686018427387904 4618441417868443648]
  [                  0 4618441417868443648 4613937818241073152
   4618441417868443648 4616189618054758400]
  [4620693217682128896 4620693217682128896 4607182418800017408
   4613937818241073152 4619567317775286272]]]


In [16]:
print(d)

[[[4. 6. 1. 7. 1.]
  [6. 6. 2. 9. 9.]
  [8. 6. 8. 1. 3.]]

 [[8. 8. 9. 3. 7.]
  [1. 7. 4. 7. 5.]
  [9. 9. 2. 4. 8.]]]


In [17]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
conditions = [(d>d_min)&(d<d_mean), (d>d_mean)&(d<d_max), d==d_mean, d==d_min, d==d_max]
replacements = [25.0,75.0,50.0,0.0,100.0]

f = np.select(conditions, replacements)
print(f)

[[[ 25.  75.   0.  75.   0.]
  [ 75.  75.  25. 100. 100.]
  [ 75.  75.  75.   0.  25.]]

 [[ 75.  75. 100.  25.  75.]
  [  0.  75.  25.  75.  25.]
  [100. 100.  25.  25.  75.]]]


In [18]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(d)
print('- - - - - - - - - - - - -')
print(f)

[[[4. 6. 1. 7. 1.]
  [6. 6. 2. 9. 9.]
  [8. 6. 8. 1. 3.]]

 [[8. 8. 9. 3. 7.]
  [1. 7. 4. 7. 5.]
  [9. 9. 2. 4. 8.]]]
- - - - - - - - - - - - -
[[[ 25.  75.   0.  75.   0.]
  [ 75.  75.  25. 100. 100.]
  [ 75.  75.  75.   0.  25.]]

 [[ 75.  75. 100.  25.  75.]
  [  0.  75.  25.  75.  25.]
  [100. 100.  25.  25.  75.]]]


In [19]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
conditions = [(d>d_min)&(d<d_mean), (d>d_mean)&(d<d_max), d==d_mean, d==d_min, d==d_max]
replacements = ['A','B','C','D','E']

f = np.select(conditions, replacements)
print(f)

[[['A' 'B' 'D' 'B' 'D']
  ['B' 'B' 'A' 'E' 'E']
  ['B' 'B' 'B' 'D' 'A']]

 [['B' 'B' 'E' 'A' 'B']
  ['D' 'B' 'A' 'B' 'A']
  ['E' 'E' 'A' 'A' 'B']]]
