In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/asair/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/asair/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/asair/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

In [8]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))

In [9]:
#4. Print a.
print(a)

[[[0.77071448 0.06392633 0.10119733 0.87359521 0.58350353]
  [0.89268764 0.67875157 0.98010024 0.73072515 0.4507016 ]
  [0.28011395 0.8581324  0.60934064 0.21532108 0.1373666 ]]

 [[0.72951114 0.80670339 0.29250353 0.62521976 0.86079379]
  [0.62802455 0.07694506 0.93621089 0.79037566 0.31969186]
  [0.66436205 0.68873259 0.72512192 0.35711693 0.08685112]]]


In [37]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

a=np.random.random((5,2,3))

TypeError: random() takes at most 1 positional argument (2 given)

In [11]:
#6. Print b.
print(b)

[[[0.35539306 0.7379617  0.10498471]
  [0.47869429 0.77305654 0.44908411]]

 [[0.88109129 0.26885922 0.83384639]
  [0.14515684 0.13724029 0.0250987 ]]

 [[0.53964092 0.21751392 0.7344456 ]
  [0.86720399 0.37515828 0.27677545]]

 [[0.14507938 0.80654779 0.14173038]
  [0.02474851 0.56481837 0.36615041]]

 [[0.72503738 0.28614698 0.00808244]
  [0.99558277 0.8887902  0.23086922]]]


In [12]:
#7. Do a and b have the same size? How do you prove that in Python code?
a == b

C:\Users\asair\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


False

In [15]:
#8. Are you able to add a and b? Why or why not?
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [16]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [38]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b,(1,2,0))
print(c)

[[[0.35539306 0.88109129 0.53964092 0.14507938 0.72503738]
  [0.7379617  0.26885922 0.21751392 0.80654779 0.28614698]
  [0.10498471 0.83384639 0.7344456  0.14173038 0.00808244]]

 [[0.47869429 0.14515684 0.86720399 0.02474851 0.99558277]
  [0.77305654 0.13724029 0.37515828 0.56481837 0.8887902 ]
  [0.44908411 0.0250987  0.27677545 0.36615041 0.23086922]]]


In [39]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a,c)
print(d)

[[[1.12610754 0.94501762 0.64083825 1.01867459 1.30854091]
  [1.63064934 0.94761079 1.19761416 1.53727294 0.73684858]
  [0.38509866 1.69197879 1.34378623 0.35705146 0.14544903]]

 [[1.20820543 0.95186023 1.15970752 0.64996827 1.85637656]
  [1.40108109 0.21418535 1.31136917 1.35519404 1.20848207]
  [1.11344616 0.71383128 1.00189738 0.72326734 0.31772034]]]


In [41]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)

[[[0.77071448 0.06392633 0.10119733 0.87359521 0.58350353]
  [0.89268764 0.67875157 0.98010024 0.73072515 0.4507016 ]
  [0.28011395 0.8581324  0.60934064 0.21532108 0.1373666 ]]

 [[0.72951114 0.80670339 0.29250353 0.62521976 0.86079379]
  [0.62802455 0.07694506 0.93621089 0.79037566 0.31969186]
  [0.66436205 0.68873259 0.72512192 0.35711693 0.08685112]]]


In [42]:
print(d)

[[[1.12610754 0.94501762 0.64083825 1.01867459 1.30854091]
  [1.63064934 0.94761079 1.19761416 1.53727294 0.73684858]
  [0.38509866 1.69197879 1.34378623 0.35705146 0.14544903]]

 [[1.20820543 0.95186023 1.15970752 0.64996827 1.85637656]
  [1.40108109 0.21418535 1.31136917 1.35519404 1.20848207]
  [1.11344616 0.71383128 1.00189738 0.72326734 0.31772034]]]


In [ ]:
#Se realizó la suma de cada elemento de acuerdo a la posición que ocupa en el array

In [43]:
#12. Multiply a and c. Assign the result to e.
e=np.multiply(a,c)
print(e)

[[[0.27390658 0.05632493 0.05461022 0.12674065 0.42306187]
  [0.65876929 0.18248862 0.21318544 0.58936476 0.1289669 ]
  [0.02940768 0.71555061 0.44752755 0.03051754 0.00111026]]

 [[0.34921282 0.11709851 0.25366023 0.01547326 0.85699146]
  [0.48549849 0.01055996 0.35122727 0.4464187  0.284139  ]
  [0.29835444 0.01728629 0.20069595 0.13075851 0.02005125]]]


In [44]:
#13. Does e equal to a? Why or why not?
a == e

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

In [ ]:
#En cuanto a estructura, a y e son iguales, sin emabrgo en resultados son distintos

In [45]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)

1.8563765567894084


In [46]:
print(d_min)

0.14544903491090266


In [47]:
print(d_mean)

1.0066377038265935


In [63]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))
print(f)

[[[0.27390658 0.05632493 0.05461022 0.12674065 0.42306187]
  [0.65876929 0.18248862 0.21318544 0.58936476 0.1289669 ]
  [0.02940768 0.71555061 0.44752755 0.03051754 0.00111026]]

 [[0.34921282 0.11709851 0.25366023 0.01547326 0.85699146]
  [0.48549849 0.01055996 0.35122727 0.4464187  0.284139  ]
  [0.29835444 0.01728629 0.20069595 0.13075851 0.02005125]]]


In [65]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for value in d:
    if d.any() >= d_min and d.any() <= d_mean:
        np.append(f, 25, axis=0)
    if d.any() >= d_mean and d.any() <= d_max:
        np.append(f, 75, axis=0)
    if d.any() == d_mean:
        np.append(f, 50, axis=0)
    if d.any() == d_max:
        np.append(f, 100, axis=0)

print(f)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 0 dimension(s)

In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.