In [2]:
#1. Import the NUMPY package under the name np.
import numpy as np
import random

#2. Print the NUMPY version and the configuration.
print(np.__version__)


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.randint(0, 100, size = (3, 2, 5))


#4. Print a.

print(a)

1.18.1
[[[54 97 25 76 68]
  [90 54 89 23 62]]

 [[18 24 79 80 99]
  [14 22  2 63 87]]

 [[ 1 55 41 17 67]
  [ 7 42 61 37 48]]]


In [3]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.random.randint(0, 100, size = (5, 2, 3))

b.fill(1)

#6. Print b.

print(b)


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [4]:
#7. Do a and b have the same size? How do you prove that in Python code?

print(a.size) 
print(b.size)

30
30


In [5]:
#8. Are you able to add a and b? Why or why not?

c = a + b

# Variable c will not run beacause operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

In [6]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.transpose(b)

print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


In [7]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c

print(d)

[[[ 55  98  26  77  69]
  [ 91  55  90  24  63]]

 [[ 19  25  80  81 100]
  [ 15  23   3  64  88]]

 [[  2  56  42  18  68]
  [  8  43  62  38  49]]]


In [8]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print('\n')
print(d)

# Our final function 'd' added 1 to each item of the matrix. 

[[[54 97 25 76 68]
  [90 54 89 23 62]]

 [[18 24 79 80 99]
  [14 22  2 63 87]]

 [[ 1 55 41 17 67]
  [ 7 42 61 37 48]]]


[[[ 55  98  26  77  69]
  [ 91  55  90  24  63]]

 [[ 19  25  80  81 100]
  [ 15  23   3  64  88]]

 [[  2  56  42  18  68]
  [  8  43  62  38  49]]]


In [9]:
#12. Multiply a and c. Assign the result to e.

e = a * c

print(e)

[[[54 97 25 76 68]
  [90 54 89 23 62]]

 [[18 24 79 80 99]
  [14 22  2 63 87]]

 [[ 1 55 41 17 67]
  [ 7 42 61 37 48]]]


In [10]:
#13. Does e equal to a? Why or why not?

(e == a)

# It is the same because each value from array 'a' was multiplied by 1. 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [11]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

100
2
51.06666666666667


In [80]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty([3,2,5],int)
f.fill(0)
print(f)

[[[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]]


In [91]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

"""
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d_mean < d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100    
print(f)

[[[ 75  75  25  75  75]
  [ 75  75  75  25  75]]

 [[ 25  25  75  75 100]
  [ 25  25  25  75  75]]

 [[  0  75  25  25  75]
  [ 25  25  75  25  25]]]


In [92]:
#17. Print d and f. Do you have your expected f?


print(d)
print('\n')
print(f)

"""
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

[[[ 55  98  26  77  69]
  [ 91  55  90  24  63]]

 [[ 19  25  80  81 100]
  [ 15  23   3  64  88]]

 [[  2  56  42  18  68]
  [  8  43  62  38  49]]]


[[[ 75  75  25  75  75]
  [ 75  75  75  25  75]]

 [[ 25  25  75  75 100]
  [ 25  25  25  75  75]]

 [[  0  75  25  25  75]
  [ 25  25  75  25  25]]]


'\nFor instance, if your d is:\narray([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],\n        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],\n        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],\n\n       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],\n        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],\n        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])\n\nYour f should be:\narray([[[ 75.,  75.,  75.,  25.,  75.],\n        [ 75.,  75.,  25.,  25.,  25.],\n        [ 75.,  25.,  75.,  75.,  75.]],\n\n       [[ 25.,  25.,  25.,  25., 100.],\n        [ 75.,  75.,  75.,  75.,  75.],\n        [ 25.,  75.,   0.,  75.,  75.]]])\n'

In [96]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 

"""
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""


g = np.empty([3,2,5],str)

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_min < d[i][j][k] < d_mean:
                g[i][j][k] = 'B'
            elif d_mean < d[i][j][k] < d_max:
                g[i][j][k] = 'D'
            elif d[i][j][k] == d_mean:
                g[i][j][k] = 'C'
            elif d[i][j][k] == d_min:
                g[i][j][k] = 'A'
            elif d[i][j][k] == d_max:
                g[i][j][k] = 'E' 

print(g)

[[['D' 'D' 'B' 'D' 'D']
  ['D' 'D' 'D' 'B' 'D']]

 [['B' 'B' 'D' 'D' 'E']
  ['B' 'B' 'B' 'D' 'D']]

 [['A' 'D' 'B' 'B' 'D']
  ['B' 'B' 'D' 'B' 'B']]]
