In [112]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [113]:
#2. Print the NUMPY version and the configuration.
np.version.version

'1.18.1'

In [114]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))


In [115]:
#4. Print a.
print(a)

[[[0.00188958 0.09347819 0.17928123 0.69051474 0.60487506]
  [0.6651032  0.05502006 0.04313282 0.12609193 0.82010693]
  [0.06417502 0.4417934  0.12209056 0.57620702 0.59069064]]

 [[0.2474954  0.13183952 0.21482968 0.29350495 0.90967026]
  [0.10096118 0.31643192 0.19704508 0.21041326 0.39177593]
  [0.79232279 0.62727891 0.34121236 0.72222396 0.0939432 ]]]


In [116]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.random.random((5,2,3))
b.fill(1)

In [117]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [118]:
#7. Do a and b have the same size? How do you prove that in Python code?
print("Tamaño inicial: ",a.shape,b.shape)
c=b.reshape((2,3,5))
print("Tamaño igual: ",a.shape,c.shape)


Tamaño inicial:  (2, 3, 5) (5, 2, 3)
Tamaño igual:  (2, 3, 5) (2, 3, 5)


In [159]:
#8. Are you able to add a and b? Why or why not?
z=np.add(a,c)
print(z,"\n\n A + B no deja por que son diferentes dimenciones pero modificando sl shape de B si deja")

[[[1.00188958 1.09347819 1.17928123 1.69051474 1.60487506]
  [1.6651032  1.05502006 1.04313282 1.12609193 1.82010693]
  [1.06417502 1.4417934  1.12209056 1.57620702 1.59069064]]

 [[1.2474954  1.13183952 1.21482968 1.29350495 1.90967026]
  [1.10096118 1.31643192 1.19704508 1.21041326 1.39177593]
  [1.79232279 1.62727891 1.34121236 1.72222396 1.0939432 ]]] 

 A + B no deja por que son diferentes dimenciones pero modificando sl shape de B si deja


In [120]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c=b.reshape((2,3,5))
print(c.shape)
print(c)

(2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [196]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c
print(d)


[[[1.00188958 1.09347819 1.17928123 1.69051474 1.60487506]
  [1.6651032  1.05502006 1.04313282 1.12609193 1.82010693]
  [1.06417502 1.4417934  1.12209056 1.57620702 1.59069064]]

 [[1.2474954  1.13183952 1.21482968 1.29350495 1.90967026]
  [1.10096118 1.31643192 1.19704508 1.21041326 1.39177593]
  [1.79232279 1.62727891 1.34121236 1.72222396 1.0939432 ]]]


In [197]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a, "\n\n",d,"\n\nTienen la misma estructura, pero los valores diferentes ya que d esta sumada con a y b atraves de c")

[[[0.00188958 0.09347819 0.17928123 0.69051474 0.60487506]
  [0.6651032  0.05502006 0.04313282 0.12609193 0.82010693]
  [0.06417502 0.4417934  0.12209056 0.57620702 0.59069064]]

 [[0.2474954  0.13183952 0.21482968 0.29350495 0.90967026]
  [0.10096118 0.31643192 0.19704508 0.21041326 0.39177593]
  [0.79232279 0.62727891 0.34121236 0.72222396 0.0939432 ]]] 

 [[[1.00188958 1.09347819 1.17928123 1.69051474 1.60487506]
  [1.6651032  1.05502006 1.04313282 1.12609193 1.82010693]
  [1.06417502 1.4417934  1.12209056 1.57620702 1.59069064]]

 [[1.2474954  1.13183952 1.21482968 1.29350495 1.90967026]
  [1.10096118 1.31643192 1.19704508 1.21041326 1.39177593]
  [1.79232279 1.62727891 1.34121236 1.72222396 1.0939432 ]]] 

Tienen la misma estructura, pero los valores diferentes ya que d esta sumada con a y b atraves de c


In [198]:
#12. Multiply a and c. Assign the result to e.
e = a*c
print(e)

[[[0.00188958 0.09347819 0.17928123 0.69051474 0.60487506]
  [0.6651032  0.05502006 0.04313282 0.12609193 0.82010693]
  [0.06417502 0.4417934  0.12209056 0.57620702 0.59069064]]

 [[0.2474954  0.13183952 0.21482968 0.29350495 0.90967026]
  [0.10096118 0.31643192 0.19704508 0.21041326 0.39177593]
  [0.79232279 0.62727891 0.34121236 0.72222396 0.0939432 ]]]


In [199]:
#13. Does e equal to a? Why or why not?
print("Son iguales por que todo lo que multipliquemos por b será el mismo al ser multiplicado por 1\n\n",a, "\n\n",e)

Son iguales por que todo lo que multipliquemos por b será el mismo al ser multiplicado por 1

 [[[0.00188958 0.09347819 0.17928123 0.69051474 0.60487506]
  [0.6651032  0.05502006 0.04313282 0.12609193 0.82010693]
  [0.06417502 0.4417934  0.12209056 0.57620702 0.59069064]]

 [[0.2474954  0.13183952 0.21482968 0.29350495 0.90967026]
  [0.10096118 0.31643192 0.19704508 0.21041326 0.39177593]
  [0.79232279 0.62727891 0.34121236 0.72222396 0.0939432 ]]] 

 [[[0.00188958 0.09347819 0.17928123 0.69051474 0.60487506]
  [0.6651032  0.05502006 0.04313282 0.12609193 0.82010693]
  [0.06417502 0.4417934  0.12209056 0.57620702 0.59069064]]

 [[0.2474954  0.13183952 0.21482968 0.29350495 0.90967026]
  [0.10096118 0.31643192 0.19704508 0.21041326 0.39177593]
  [0.79232279 0.62727891 0.34121236 0.72222396 0.0939432 ]]]


In [200]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max,d_min,d_mean)

1.9096702606531188 1.0018895819648517 1.3555132928378606


In [201]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))
f=d.copy()
print(f)

[[[1.00188958 1.09347819 1.17928123 1.69051474 1.60487506]
  [1.6651032  1.05502006 1.04313282 1.12609193 1.82010693]
  [1.06417502 1.4417934  1.12209056 1.57620702 1.59069064]]

 [[1.2474954  1.13183952 1.21482968 1.29350495 1.90967026]
  [1.10096118 1.31643192 1.19704508 1.21041326 1.39177593]
  [1.79232279 1.62727891 1.34121236 1.72222396 1.0939432 ]]]


In [202]:
"""
#16. Populate the values in f. For each value in d, 
if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
i=0
j=0
k=0
for l in f:  
    j=0
    for m in f[i]:
        k=0
        for n in f[i,j]:
            if f[i,j,k] > d_min and f[i,j,k] < d_mean:
                f[i,j,k]=25
            if f[i,j,k] > d_mean and f[i,j,k] < d_max:
                f[i,j,k]=75
            if f[i,j,k] == d_mean:
                f[i,j,k]=50
            if f[i,j,k] == d_min:
                f[i,j,k]=0
            if f[i,j,k] == d_max:
                f[i,j,k]=100
            k+=1
        j+=1
    i+=1
print(f)




[[[  0.  25.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]]]


In [206]:

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print("Matriz d:\n",d,"\n\nMatriz f:\n",f)

Matriz d:
 [[[1.00188958 1.09347819 1.17928123 1.69051474 1.60487506]
  [1.6651032  1.05502006 1.04313282 1.12609193 1.82010693]
  [1.06417502 1.4417934  1.12209056 1.57620702 1.59069064]]

 [[1.2474954  1.13183952 1.21482968 1.29350495 1.90967026]
  [1.10096118 1.31643192 1.19704508 1.21041326 1.39177593]
  [1.79232279 1.62727891 1.34121236 1.72222396 1.0939432 ]]] 

Matriz f:
 [[[  0.  25.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]]]


In [223]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
g = np.empty((2,3,5))
g=d.copy()
h=np.empty((2,3,5),dtype=object)
#print(h)
i=0
j=0
k=0
for l in g:  
    j=0
    for m in g[i]:
        k=0
        for n in g[i,j]:
            if g[i,j,k] > d_min and g[i,j,k] < d_mean:
                h[i,j,k]="A"
            if g[i,j,k] > d_mean and g[i,j,k] < d_max:
                h[i,j,k]="B"
            if g[i,j,k] == d_mean:
                h[i,j,k]="C"
            if g[i,j,k] == d_min:
                h[i,j,k]="D"
            if g[i,j,k] == d_max:
                h[i,j,k]="E"
            k+=1
        j+=1
    i+=1

print("Matriz d:\n",d,"\n\nMatriz h:\n",h)


Matriz d:
 [[[1.00188958 1.09347819 1.17928123 1.69051474 1.60487506]
  [1.6651032  1.05502006 1.04313282 1.12609193 1.82010693]
  [1.06417502 1.4417934  1.12209056 1.57620702 1.59069064]]

 [[1.2474954  1.13183952 1.21482968 1.29350495 1.90967026]
  [1.10096118 1.31643192 1.19704508 1.21041326 1.39177593]
  [1.79232279 1.62727891 1.34121236 1.72222396 1.0939432 ]]] 

Matriz h:
 [[['D' 'A' 'A' 'B' 'B']
  ['B' 'A' 'A' 'A' 'B']
  ['A' 'B' 'A' 'B' 'B']]

 [['A' 'A' 'A' 'A' 'E']
  ['A' 'A' 'A' 'A' 'B']
  ['B' 'B' 'A' 'B' 'A']]]
