In [2]:
import numpy as np

In [3]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX

In [5]:
#forma 1 
'''
a = np.random.random((2,3,5))
print(a)'''
#forma 2
'''
c = np.random.rand(2,3,5)
print(c)
'''
#FORMA 3
a = np.random.randint(1,10, size =(2,3,5))

[[[5 7 1 2 6]
  [7 7 5 9 7]
  [5 5 3 2 9]]

 [[6 2 9 7 6]
  [3 9 8 7 7]
  [7 1 5 3 5]]]


In [7]:
print(a)

[[[5 7 1 2 6]
  [7 7 5 9 7]
  [5 5 3 2 9]]

 [[6 2 9 7 6]
  [3 9 8 7 7]
  [7 1 5 3 5]]]


In [8]:
#FORMA 1
'''
b = np.random.randint(1,2, size =(5,2,3))
print(b)
'''
#FORMA 2
b = np.ones((5,2,3))

In [10]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [12]:
print('size (a):',np.size(a))
print('shape (a):',np.shape(a))

print('size (b):',np.size(b))
print('shape (b:)',np.shape(b))

size (a): 30
shape (a): (2, 3, 5)
size (b): 30
shape (b:) (5, 2, 3)


In [13]:
print('ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) ')
print('Tiene distinta forma, de contruccion')

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
Tiene distinta forma, de contruccion


In [14]:
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [15]:
d = a +c
print('matriz a y c , ya tiene la misma estructura de 2,3,5')

matriz a y c , ya tiene la misma estructura de 2,3,5


In [16]:
print(d)


[[[ 6.  8.  2.  3.  7.]
  [ 8.  8.  6. 10.  8.]
  [ 6.  6.  4.  3. 10.]]

 [[ 7.  3. 10.  8.  7.]
  [ 4. 10.  9.  8.  8.]
  [ 8.  2.  6.  4.  6.]]]


In [18]:
e = a*c

In [19]:
print('b esta definido por unos , pero flotantes, por lo que al multiplicarse se vuelven valores flotantes en el caso de F')
print(e)


b esta definido por unos , pero flotantes, por lo que al multiplicarse se vuelven valores flotantes en el caso de F
[[[5. 7. 1. 2. 6.]
  [7. 7. 5. 9. 7.]
  [5. 5. 3. 2. 9.]]

 [[6. 2. 9. 7. 6.]
  [3. 9. 8. 7. 7.]
  [7. 1. 5. 3. 5.]]]


In [20]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print('d_min:\t',d_min)
print('d_max:\t',d_max)
print('d_mean:\t',d_mean)

d_min:	 2.0
d_max:	 10.0
d_mean:	 6.5


In [22]:
f = np.empty([2,3,5])
print('f np.empty: \n',f)

f np.empty: 
 [[[5. 7. 1. 2. 6.]
  [7. 7. 5. 9. 7.]
  [5. 5. 3. 2. 9.]]

 [[6. 2. 9. 7. 6.]
  [3. 9. 8. 7. 7.]
  [7. 1. 5. 3. 5.]]]


In [23]:
f = np.where((d_mean > d)&(d > d_min), 25, 
             np.where((d_mean < d)&(d < d_max), 75,
                      np.where(d == d_max, 100,
                              np.where(d == d_mean, 50, 0)
                              )
                     )
            )
print('F nueva con condiciones \n de D',f)

F nueva con condiciones 
 de D [[[ 25  75   0  25  75]
  [ 75  75  25 100  75]
  [ 25  25  25  25 100]]

 [[ 75  25 100  75  75]
  [ 25 100  75  75  75]
  [ 75   0  25  25  25]]]


In [25]:
d1 = ([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

print('D1\n',d1)

f1 = np.empty([2,3,5])
print('F1:\n',f1)

d1_max = np.max(d1)
d1_min = np.min(d1)
d1_mean = np.mean(d1)

print('d_min:\t',d1_min)
print('d_max:\t',d1_max)
print('d_mean:\t',d1_mean)

f1 = np.where((d1_mean > d1)&(d1 > d1_min), 25, 
             np.where((d1_mean < d1)&(d1 < d1_max), 75,
                      np.where(d1 == d1_max, 100,
                              np.where(d1 == d1_mean, 50, 0)
                              )
                     )
            )

print('F1 ESPERADA EJEMPLO:','\n',f1)

D1
 [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918, 1.87078449, 1.7726778, 1.88180042]], [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381], [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881], [1.18068344, 1.9587381, 1.00656599, 1.93402165, 1.73514584]]]
F1:
 [[[5. 7. 1. 2. 6.]
  [7. 7. 5. 9. 7.]
  [5. 5. 3. 2. 9.]]

 [[6. 2. 9. 7. 6.]
  [3. 9. 8. 7. 7.]
  [7. 1. 5. 3. 5.]]]
d_min:	 1.00656599
d_max:	 1.97066381
d_mean:	 1.6175069086666667
F1 ESPERADA EJEMPLO: 
 [[[ 75  75  75  25  75]
  [ 75  75  25  25  25]
  [ 75  25  75  75  75]]

 [[ 25  25  25  25 100]
  [ 75  75  75  75  75]
  [ 25  75   0  75  75]]]


In [26]:
f1 = np.where((d_mean > d)&(d > d_min), 'B', 
             np.where((d_mean < d)&(d < d_max), 'D',
                      np.where(d == d_max, 'E',
                              np.where(d == d_mean, 'C', 'A')
                              )
                     )
            )

print('PRINT DE EJERCICIO PERSONAL: \n',f)


f2 = np.empty([2,3,5])

f2 = np.where((d1_mean > d1)&(d1 > d1_min), 'B', 
             np.where((d1_mean < d1)&(d1 < d1_max), 'D',
                      np.where(d1 == d1_max, 'E',
                              np.where(d1 == d1_mean, 'C', 'A')
                              )
                     )
            )
                               
print('PRINT DE EJEMPLO 17 Y 18\n',f2)

PRINT DE EJERCICIO PERSONAL: 
 [[[ 25  75   0  25  75]
  [ 75  75  25 100  75]
  [ 25  25  25  25 100]]

 [[ 75  25 100  75  75]
  [ 25 100  75  75  75]
  [ 75   0  25  25  25]]]
PRINT DE EJEMPLO 17 Y 18
 [[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
