In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [ ]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
a = np.random.random((2,3,5))

In [29]:
#4. Print a.
print(a)
print(a.shape)

[[[0.94909959 0.05746008 0.49481124 0.84608901 0.46595802]
  [0.15214088 0.33043563 0.51744971 0.7347213  0.77277887]
  [0.84776831 0.92832275 0.89984422 0.68482447 0.48605918]]

 [[0.55364609 0.20645631 0.8093515  0.29027471 0.26082705]
  [0.55029208 0.07554715 0.37436598 0.9378983  0.4886881 ]
  [0.20353966 0.5218034  0.29924192 0.3032968  0.91186091]]]
(2, 3, 5)


In [34]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b=np.random.random((5,3,2))
b.fill(1)

In [35]:
#6. Print b.
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [36]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.shape)
print(b.shape)
print(a==b) # con la operación booleana comprobamos que no son del mismo tamaño

(2, 3, 5)
(5, 3, 2)
False


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  after removing the cwd from sys.path.


In [37]:
#8. Are you able to add a and b? Why or why not?
a+b
# el error nos dice que debido a que no son del mismo tamaño no se pueden sumar

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

In [38]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c=b.transpose()
print(c)
print(c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


In [40]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=a+c
print(d)
# la suma es posible porque tienen el mismo tamaño
# se tuvo que modificar el ejercicio 5

[[[1.94909959 1.05746008 1.49481124 1.84608901 1.46595802]
  [1.15214088 1.33043563 1.51744971 1.7347213  1.77277887]
  [1.84776831 1.92832275 1.89984422 1.68482447 1.48605918]]

 [[1.55364609 1.20645631 1.8093515  1.29027471 1.26082705]
  [1.55029208 1.07554715 1.37436598 1.9378983  1.4886881 ]
  [1.20353966 1.5218034  1.29924192 1.3032968  1.91186091]]]


In [43]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print('--------------------------------------------------------------------------')
print(d)
# La diferencia de los valores de 'a' y 'd' es 1, debido a que la columna 'c' son relleno con 1's 

[[[0.94909959 0.05746008 0.49481124 0.84608901 0.46595802]
  [0.15214088 0.33043563 0.51744971 0.7347213  0.77277887]
  [0.84776831 0.92832275 0.89984422 0.68482447 0.48605918]]

 [[0.55364609 0.20645631 0.8093515  0.29027471 0.26082705]
  [0.55029208 0.07554715 0.37436598 0.9378983  0.4886881 ]
  [0.20353966 0.5218034  0.29924192 0.3032968  0.91186091]]]
--------------------------------------------------------------------------
[[[1.94909959 1.05746008 1.49481124 1.84608901 1.46595802]
  [1.15214088 1.33043563 1.51744971 1.7347213  1.77277887]
  [1.84776831 1.92832275 1.89984422 1.68482447 1.48605918]]

 [[1.55364609 1.20645631 1.8093515  1.29027471 1.26082705]
  [1.55029208 1.07554715 1.37436598 1.9378983  1.4886881 ]
  [1.20353966 1.5218034  1.29924192 1.3032968  1.91186091]]]


In [45]:
#12. Multiply a and c. Assign the result to e.
e=a*c

[[[0.94909959 0.05746008 0.49481124 0.84608901 0.46595802]
  [0.15214088 0.33043563 0.51744971 0.7347213  0.77277887]
  [0.84776831 0.92832275 0.89984422 0.68482447 0.48605918]]

 [[0.55364609 0.20645631 0.8093515  0.29027471 0.26082705]
  [0.55029208 0.07554715 0.37436598 0.9378983  0.4886881 ]
  [0.20353966 0.5218034  0.29924192 0.3032968  0.91186091]]]


In [46]:
#13. Does e equal to a? Why or why not?
# es el mismo valor ya que cualquier valor multiplicado por la unidad seguira siendo el mismo valor
print(e)
print('--------------------------------------------------------------------------')
print(a)

[[[0.94909959 0.05746008 0.49481124 0.84608901 0.46595802]
  [0.15214088 0.33043563 0.51744971 0.7347213  0.77277887]
  [0.84776831 0.92832275 0.89984422 0.68482447 0.48605918]]

 [[0.55364609 0.20645631 0.8093515  0.29027471 0.26082705]
  [0.55029208 0.07554715 0.37436598 0.9378983  0.4886881 ]
  [0.20353966 0.5218034  0.29924192 0.3032968  0.91186091]]]
--------------------------------------------------------------------------
[[[0.94909959 0.05746008 0.49481124 0.84608901 0.46595802]
  [0.15214088 0.33043563 0.51744971 0.7347213  0.77277887]
  [0.84776831 0.92832275 0.89984422 0.68482447 0.48605918]]

 [[0.55364609 0.20645631 0.8093515  0.29027471 0.26082705]
  [0.55029208 0.07554715 0.37436598 0.9378983  0.4886881 ]
  [0.20353966 0.5218034  0.29924192 0.3032968  0.91186091]]]


In [49]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_mean=d.mean()
d_max=d.max()
d_min=d.min()
print(d_mean, d_max, d_min)

1.5318284405212899 1.949099587095123 1.05746007790379


In [69]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty([2,3,5],float)
print(f)
print('---------------------------------------------------------------------------')
print(d)

[[[0.94909959 0.05746008 0.49481124 0.84608901 0.46595802]
  [0.15214088 0.33043563 0.51744971 0.7347213  0.77277887]
  [0.84776831 0.92832275 0.89984422 0.68482447 0.48605918]]

 [[0.55364609 0.20645631 0.8093515  0.29027471 0.26082705]
  [0.55029208 0.07554715 0.37436598 0.9378983  0.4886881 ]
  [0.20353966 0.5218034  0.29924192 0.3032968  0.91186091]]]
---------------------------------------------------------------------------
[[[1.94909959 1.05746008 1.49481124 1.84608901 1.46595802]
  [1.15214088 1.33043563 1.51744971 1.7347213  1.77277887]
  [1.84776831 1.92832275 1.89984422 1.68482447 1.48605918]]

 [[1.55364609 1.20645631 1.8093515  1.29027471 1.26082705]
  [1.55029208 1.07554715 1.37436598 1.9378983  1.4886881 ]
  [1.20353966 1.5218034  1.29924192 1.3032968  1.91186091]]]


In [111]:

#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, 
#    assign 25 to the corresponding value in f.
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
# If a value equals to d_mean, assign 50 to the corresponding value in f.
# Assign 0 to the corresponding value(s) in f for d_min in d.
# Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, and 100.
# Note: you don't have to use Numpy in this question.
subsf=f.copy()
print(subsf)

[[[0.94909959 0.05746008 0.49481124 0.84608901 0.46595802]
  [0.15214088 0.33043563 0.51744971 0.7347213  0.77277887]
  [0.84776831 0.92832275 0.89984422 0.68482447 0.48605918]]

 [[0.55364609 0.20645631 0.8093515  0.29027471 0.26082705]
  [0.55029208 0.07554715 0.37436598 0.9378983  0.4886881 ]
  [0.20353966 0.5218034  0.29924192 0.3032968  0.91186091]]]


In [161]:
# Ejercicio 17
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if (d[i][j][k] > d_min) and (d[i][j][k] < d_mean):
                subsf[i][j][k]=25
            elif (d[i][j][k] > d_mean) and (d[i][j][k] < d_max):
                subsf[i][j][k]=75
            elif (d[i][j][k] == d_min):
                subsf[i][j][k] = 0
            elif (d[i][j][k] == d_mean):
                subsf[i][j][k] = 50
            elif (d[i][j][k] == d_max):
                subsf[i][j][k] = 100
print(subsf)
np.shape(subsf)

[[[100.   0.  25.  75.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  75.  75.  75.  25.]]

 [[ 75.  25.  75.  25.  25.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.  25.  75.]]]


(2, 3, 5)

In [164]:
# Ejercicio 18 Bonus
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
# array([[[ 'D',  'D',  'D',  'B',  'D'],
#         [ 'D',  'D',  'B',  'B',  'B'],
#         [ 'D',  'B',  'D',  'D',  'D']],
#
#        [[ 'B',  'B',  'B',  'B',  'E'],
#         [ 'D',  'D',  'D',  'D',  'D'],
#         [ 'B',  'D',   'A',  'D', 'D']]])
# Again, you don't need Numpy in this question.

letrasf = subsf.copy()
l=np.array(letrasf[2, 3, 5], dtype='str')
for i in range(len(l)):
    for j in range(len(l[i])):
        for k in range(len(l[i][j])):
            if (l[i][j][k] == '0'):
                letrasf[i][j][k]= 'A'
            elif (l[i][j][k] == '25'):
                letrasf[i][j][k]= 'B'
            elif (l[i][j][k] == '50'):
                letrasf[i][j][k] = 'C'
            elif (l[i][j][k] == '75'):
                letrasf[i][j][k] = 'D'
            elif (l[i][j][k] == '100'):
                letrasf[i][j][k] = 'E'
print(letrasf)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
for i in letrasff:
    if i == '0':
        i = 'A'
    elif i == '25':
        i = 'B'
    elif i == '50':
        i = 'C'
    elif i == '75':
        i = 'D'
    elif i == '100':
        i = 'E'