#1. Import the NUMPY package under the name np.

In [3]:
import numpy as np


#2. Print the NUMPY version and the configuration.


In [5]:
print(np.__version__)

1.21.5


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
#way 1
a=np.random.random((2,3,5))
a

array([[[0.17025875, 0.41141824, 0.32073386, 0.74336145, 0.38359115],
        [0.17191069, 0.74072103, 0.50690604, 0.49899863, 0.35176772],
        [0.60657751, 0.83619432, 0.41613756, 0.5730882 , 0.63122102]],

       [[0.90189754, 0.63717155, 0.10068755, 0.12805949, 0.89402187],
        [0.40086939, 0.99102283, 0.90708224, 0.1820493 , 0.54836366],
        [0.28507046, 0.46738342, 0.59414774, 0.78066691, 0.00367048]]])

In [11]:
#way2 
a=np.random.sample((2,3,5))
a

array([[[0.66687923, 0.05922013, 0.37485253, 0.17605071, 0.88098097],
        [0.30020557, 0.77194224, 0.92539106, 0.7175836 , 0.21165136],
        [0.02488021, 0.68569977, 0.66809404, 0.31407782, 0.37584337]],

       [[0.15827245, 0.80343348, 0.9628553 , 0.78126768, 0.52390444],
        [0.49276219, 0.13648323, 0.69632707, 0.63152024, 0.66733276],
        [0.33766193, 0.64764177, 0.58816922, 0.34706804, 0.01194322]]])

#4. Print a.

In [13]:
print(a)

[[[0.66687923 0.05922013 0.37485253 0.17605071 0.88098097]
  [0.30020557 0.77194224 0.92539106 0.7175836  0.21165136]
  [0.02488021 0.68569977 0.66809404 0.31407782 0.37584337]]

 [[0.15827245 0.80343348 0.9628553  0.78126768 0.52390444]
  [0.49276219 0.13648323 0.69632707 0.63152024 0.66733276]
  [0.33766193 0.64764177 0.58816922 0.34706804 0.01194322]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [19]:
b=np.ones((5,2,3))

#6. Print b.


In [21]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [23]:
a.size


30

In [25]:
b.size

30

In [30]:
if a.size==b.size:
    print('a & b have the same size')
else:
    print('a & b do not have the same size')

a & b have the same size



#8. Are you able to add a and b? Why or why not?

In [32]:
c=a+b
#It can not be possible to add a & b because they do not share the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [35]:
c=np.transpose(b)

In [37]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [48]:
c.reshape(2,3,5)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [49]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [50]:
c.shape

(2, 3, 5)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [51]:
d=a+c

In [52]:
d


array([[[1.66687923, 1.05922013, 1.37485253, 1.17605071, 1.88098097],
        [1.30020557, 1.77194224, 1.92539106, 1.7175836 , 1.21165136],
        [1.02488021, 1.68569977, 1.66809404, 1.31407782, 1.37584337]],

       [[1.15827245, 1.80343348, 1.9628553 , 1.78126768, 1.52390444],
        [1.49276219, 1.13648323, 1.69632707, 1.63152024, 1.66733276],
        [1.33766193, 1.64764177, 1.58816922, 1.34706804, 1.01194322]]])

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [54]:
a

array([[[0.66687923, 0.05922013, 0.37485253, 0.17605071, 0.88098097],
        [0.30020557, 0.77194224, 0.92539106, 0.7175836 , 0.21165136],
        [0.02488021, 0.68569977, 0.66809404, 0.31407782, 0.37584337]],

       [[0.15827245, 0.80343348, 0.9628553 , 0.78126768, 0.52390444],
        [0.49276219, 0.13648323, 0.69632707, 0.63152024, 0.66733276],
        [0.33766193, 0.64764177, 0.58816922, 0.34706804, 0.01194322]]])

In [57]:
d

array([[[1.66687923, 1.05922013, 1.37485253, 1.17605071, 1.88098097],
        [1.30020557, 1.77194224, 1.92539106, 1.7175836 , 1.21165136],
        [1.02488021, 1.68569977, 1.66809404, 1.31407782, 1.37584337]],

       [[1.15827245, 1.80343348, 1.9628553 , 1.78126768, 1.52390444],
        [1.49276219, 1.13648323, 1.69632707, 1.63152024, 1.66733276],
        [1.33766193, 1.64764177, 1.58816922, 1.34706804, 1.01194322]]])

#12. Multiply a and c. Assign the result to e.


In [61]:
e=a*c


In [62]:
e

array([[[0.66687923, 0.05922013, 0.37485253, 0.17605071, 0.88098097],
        [0.30020557, 0.77194224, 0.92539106, 0.7175836 , 0.21165136],
        [0.02488021, 0.68569977, 0.66809404, 0.31407782, 0.37584337]],

       [[0.15827245, 0.80343348, 0.9628553 , 0.78126768, 0.52390444],
        [0.49276219, 0.13648323, 0.69632707, 0.63152024, 0.66733276],
        [0.33766193, 0.64764177, 0.58816922, 0.34706804, 0.01194322]]])

#13. Does e equal to a? Why or why not?

In [73]:
#array_equal= returns True if input arrays are shape consistent and all elements equal
if np.array_equal(a,e):
    print("a & e are the same")
else:
    print("a & e are not the same")

a & e are the same


#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [67]:
d_min=d.min()
d_max=d.max()
d_mean=d.mean()

In [69]:
print(d_min)
print(d_max)
print(d_mean)

1.011943219387294
1.9628552959844001
1.4979998545854707


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [75]:
f=np.empty([2,3,5])

"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [86]:
#numpy.nditer=Efficient multi-dimensional iterator object to iterate over arrays

f=[]
for i in np.nditer(d):
    if d_min < i < d_mean:
        f+=[25]
    if d_mean < i < d_max:
        f +=[75]
    if i == d_mean:
        f+=[50]
    if i == d_min:
        f +=[0]
    if i ==d_max:
        f +=[100]
f=np.reshape(f,d.shape)
print(f)
    

[[[ 75  25  25  25  75]
  [ 25  75  75  75  25]
  [ 25  75  75  25  25]]

 [[ 25  75 100  75  75]
  [ 25  25  75  75  75]
  [ 25  75  75  25   0]]]


"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [88]:
print(d)

[[[1.66687923 1.05922013 1.37485253 1.17605071 1.88098097]
  [1.30020557 1.77194224 1.92539106 1.7175836  1.21165136]
  [1.02488021 1.68569977 1.66809404 1.31407782 1.37584337]]

 [[1.15827245 1.80343348 1.9628553  1.78126768 1.52390444]
  [1.49276219 1.13648323 1.69632707 1.63152024 1.66733276]
  [1.33766193 1.64764177 1.58816922 1.34706804 1.01194322]]]


In [90]:
print(f)

[[[ 75  25  25  25  75]
  [ 25  75  75  75  25]
  [ 25  75  75  25  25]]

 [[ 25  75 100  75  75]
  [ 25  25  75  75  75]
  [ 25  75  75  25   0]]]



"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [95]:
#numpy.nditer=Efficient multi-dimensional iterator object to iterate over arrays
g=[]
for j in np.nditer(d):
    if d_min < j < d_mean:
        g+=['B']
    if d_mean < j < d_max:
        g +=['D']
    if j == d_mean:
        g+=['C']
    if j == d_min:
        g +=['A']
    if j ==d_max:
        g +=['E']
g=np.reshape(g,d.shape)
print(g)

[[['D' 'B' 'B' 'B' 'D']
  ['B' 'D' 'D' 'D' 'B']
  ['B' 'D' 'D' 'B' 'B']]

 [['B' 'D' 'E' 'D' 'D']
  ['B' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'B' 'A']]]
