#1. Import the NUMPY package under the name np.


In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.



In [4]:
print(np.__version__)

1.20.2


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
#Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?



In [3]:
# Method_1

a = np.random.random((2,3,5))

a

array([[[0.47170417, 0.65893307, 0.79910228, 0.26637092, 0.12709129],
        [0.14662835, 0.15790513, 0.84735255, 0.91226002, 0.06019453],
        [0.60998385, 0.21399586, 0.71566857, 0.03809507, 0.26209272]],

       [[0.6591343 , 0.0671747 , 0.469147  , 0.92315535, 0.19758461],
        [0.79357583, 0.03180768, 0.45467975, 0.12011119, 0.47972135],
        [0.91087231, 0.06833998, 0.78654842, 0.64523418, 0.56749982]]])

In [5]:
# Method_2

a = np.random.sample((2,3,5))

a

array([[[0.74287001, 0.76065921, 0.44739795, 0.28749184, 0.01857338],
        [0.82455888, 0.67150364, 0.99290188, 0.87629437, 0.98651162],
        [0.17520523, 0.46968244, 0.60571639, 0.91820325, 0.71944795]],

       [[0.1308814 , 0.66773799, 0.55967138, 0.84384984, 0.84251545],
        [0.15995043, 0.44320042, 0.56487305, 0.46174724, 0.11222415],
        [0.50789299, 0.51982994, 0.66494504, 0.92842389, 0.78965627]]])

In [8]:
# Method_3

a = np.random.rand(2,3,5)

a

array([[[0.38599712, 0.92639755, 0.84463653, 0.71919786, 0.5214361 ],
        [0.07946926, 0.4230369 , 0.6961126 , 0.18790453, 0.15697763],
        [0.02152038, 0.48377616, 0.16689783, 0.71624802, 0.1243263 ]],

       [[0.91745883, 0.95854149, 0.15988643, 0.26541625, 0.65456576],
        [0.3654516 , 0.44915478, 0.51700422, 0.07650357, 0.61012424],
        [0.36785723, 0.12057612, 0.75074789, 0.64831588, 0.82961348]]])

#4. Print a.

In [9]:
print(a)

[[[0.38599712 0.92639755 0.84463653 0.71919786 0.5214361 ]
  [0.07946926 0.4230369  0.6961126  0.18790453 0.15697763]
  [0.02152038 0.48377616 0.16689783 0.71624802 0.1243263 ]]

 [[0.91745883 0.95854149 0.15988643 0.26541625 0.65456576]
  [0.3654516  0.44915478 0.51700422 0.07650357 0.61012424]
  [0.36785723 0.12057612 0.75074789 0.64831588 0.82961348]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [12]:
b = np.ones((5,2,3))

b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#4. Print b.

In [13]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
