In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Tania/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Tania/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Tania/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Tania/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Tania/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Tania/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Tania/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Tania/anaconda3\\Library\\include']
None


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
#np.random.rand(2,3,5) llena de  números aleatorios entre cero y 1
a = np.random.random((2,3,5))


In [4]:
#4. Print a.
print(a)

[[[0.29057108 0.78083715 0.21461933 0.31693685 0.00186377]
  [0.23522512 0.94001998 0.17134013 0.8851236  0.89174077]
  [0.79367091 0.28001089 0.11917801 0.95861795 0.51579992]]

 [[0.77195555 0.20554946 0.4708228  0.95942996 0.00224431]
  [0.02449141 0.21085901 0.67645596 0.35057389 0.57573966]
  [0.95767717 0.71964547 0.54174563 0.50244966 0.29291625]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
#tenia que ser un array de 5x3x2 para que su transpuesta coincida mas adelante con a
b=np.ones((5,3,2)) 



In [6]:
#6. Print b.
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code? 
#con size
print(a.size) 
print(b.size)

30
30


In [8]:
#8. Are you able to add a and b? Why or why not?
#no, porque no tienen los mismos shapes

In [9]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c=b.T

In [10]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=np.add(a, c)
d

array([[[1.29057108, 1.78083715, 1.21461933, 1.31693685, 1.00186377],
        [1.23522512, 1.94001998, 1.17134013, 1.8851236 , 1.89174077],
        [1.79367091, 1.28001089, 1.11917801, 1.95861795, 1.51579992]],

       [[1.77195555, 1.20554946, 1.4708228 , 1.95942996, 1.00224431],
        [1.02449141, 1.21085901, 1.67645596, 1.35057389, 1.57573966],
        [1.95767717, 1.71964547, 1.54174563, 1.50244966, 1.29291625]]])

In [11]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)

#A cada elemento de la matriz a se le sumo el elemento correspondiente de la matriz c (todos los elementos eran 1) 
#así que cada elemento de d es el elemnto de a +1

[[[0.29057108 0.78083715 0.21461933 0.31693685 0.00186377]
  [0.23522512 0.94001998 0.17134013 0.8851236  0.89174077]
  [0.79367091 0.28001089 0.11917801 0.95861795 0.51579992]]

 [[0.77195555 0.20554946 0.4708228  0.95942996 0.00224431]
  [0.02449141 0.21085901 0.67645596 0.35057389 0.57573966]
  [0.95767717 0.71964547 0.54174563 0.50244966 0.29291625]]]
[[[1.29057108 1.78083715 1.21461933 1.31693685 1.00186377]
  [1.23522512 1.94001998 1.17134013 1.8851236  1.89174077]
  [1.79367091 1.28001089 1.11917801 1.95861795 1.51579992]]

 [[1.77195555 1.20554946 1.4708228  1.95942996 1.00224431]
  [1.02449141 1.21085901 1.67645596 1.35057389 1.57573966]
  [1.95767717 1.71964547 1.54174563 1.50244966 1.29291625]]]


In [12]:
#12. Multiply a and c. Assign the result to e.
e=np.multiply(a, c)

In [13]:
#13. Does e equal to a? Why or why not?
print(a)
print(e)
"si son iguales porque se multiplica entrada por entrada"

[[[0.29057108 0.78083715 0.21461933 0.31693685 0.00186377]
  [0.23522512 0.94001998 0.17134013 0.8851236  0.89174077]
  [0.79367091 0.28001089 0.11917801 0.95861795 0.51579992]]

 [[0.77195555 0.20554946 0.4708228  0.95942996 0.00224431]
  [0.02449141 0.21085901 0.67645596 0.35057389 0.57573966]
  [0.95767717 0.71964547 0.54174563 0.50244966 0.29291625]]]
[[[0.29057108 0.78083715 0.21461933 0.31693685 0.00186377]
  [0.23522512 0.94001998 0.17134013 0.8851236  0.89174077]
  [0.79367091 0.28001089 0.11917801 0.95861795 0.51579992]]

 [[0.77195555 0.20554946 0.4708228  0.95942996 0.00224431]
  [0.02449141 0.21085901 0.67645596 0.35057389 0.57573966]
  [0.95767717 0.71964547 0.54174563 0.50244966 0.29291625]]]


'si son iguales porque se multiplica entrada por entrada'

In [14]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_mean=np.mean(d)
d_max=np.max(d)
d_min=np.min(d)
print(d_mean)
print(d_max)
print(d_min)

1.4886037210377256
1.9594299639420125
1.0018637749345578


In [15]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty((2,3,5))
print (d)
print(f)

[[[1.29057108 1.78083715 1.21461933 1.31693685 1.00186377]
  [1.23522512 1.94001998 1.17134013 1.8851236  1.89174077]
  [1.79367091 1.28001089 1.11917801 1.95861795 1.51579992]]

 [[1.77195555 1.20554946 1.4708228  1.95942996 1.00224431]
  [1.02449141 1.21085901 1.67645596 1.35057389 1.57573966]
  [1.95767717 1.71964547 1.54174563 1.50244966 1.29291625]]]
[[[0.29057108 0.78083715 0.21461933 0.31693685 0.00186377]
  [0.23522512 0.94001998 0.17134013 0.8851236  0.89174077]
  [0.79367091 0.28001089 0.11917801 0.95861795 0.51579992]]

 [[0.77195555 0.20554946 0.4708228  0.95942996 0.00224431]
  [0.02449141 0.21085901 0.67645596 0.35057389 0.57573966]
  [0.95767717 0.71964547 0.54174563 0.50244966 0.29291625]]]


In [22]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
for i in range(2):
    for j in range(3):
        for k in range (5):
            if  d_min<d[i,j,k] and d[i,j,k]<d_mean:
                f[i,j,k]=25
            elif d_mean<d[i,j,k] and d[i,j,k]<d_max:
                f[i,j,k]=75
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50 
            elif d[i,j,k]==d_min:
                f[i,j,k]=0
            elif d[i,j,k]==d_max:
                f[i,j,k]=100
    


In [23]:

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(f)

[[[ 25.  75.  25.  25.   0.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[ 75.  25.  25. 100.  25.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75.  75.  75.  25.]]]


In [36]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

for i in range(2):
    for j in range(3):
        for k in range (5):
            if  d_min<d[i,j,k] and d[i,j,k]<d_mean:
                f[i,j,k]="B"
            elif d_mean<d[i,j,k] and d[i,j,k]<d_max:
                f[i,j,k]="D"
            elif d[i,j,k]==d_mean:
                f[i,j,k]="C"
            elif d[i,j,k]==d_min:
                f[i,j,k]="A"
            elif d[i,j,k]==d_max:
                f[i,j,k]="E"
"No doy con como modificarlo para que corra "

ValueError: could not convert string to float: 'B'