In [4]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [7]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)

1.21.2


In [82]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a= np.random.random((2,3,5))


In [83]:
#4. Print a.
print(a)

[[[0.72338693 0.53681583 0.83288232 0.01665714 0.13286795]
  [0.84023085 0.62375665 0.65764074 0.23518552 0.48974744]
  [0.56620855 0.8027896  0.4710776  0.73136086 0.29454315]]

 [[0.01097347 0.08647883 0.94306489 0.00220362 0.68400928]
  [0.04580086 0.35909794 0.66364167 0.249146   0.86858029]
  [0.91020944 0.51424145 0.59611173 0.98075819 0.5231338 ]]]


In [ ]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [84]:
b = np.ones((5,2,3))
print(b)
# b=np.zeros((5,2,3))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [46]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(np.array_equal(a,b))

False


In [49]:
#8. Are you able to add a and b? Why or why not?
# d = np.concatenate((a, b))     Not possible becase the array dimensions are different

In [85]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b,(1,2,0))
print(c)





[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [86]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c

In [87]:
d

array([[[1.72338693, 1.53681583, 1.83288232, 1.01665714, 1.13286795],
        [1.84023085, 1.62375665, 1.65764074, 1.23518552, 1.48974744],
        [1.56620855, 1.8027896 , 1.4710776 , 1.73136086, 1.29454315]],

       [[1.01097347, 1.08647883, 1.94306489, 1.00220362, 1.68400928],
        [1.04580086, 1.35909794, 1.66364167, 1.249146  , 1.86858029],
        [1.91020944, 1.51424145, 1.59611173, 1.98075819, 1.5231338 ]]])

In [81]:
a

array([[[0.16818462, 0.78039141, 0.53531993, 0.71345708, 0.38713402],
        [0.67048767, 0.76623942, 0.54688915, 0.49190149, 0.01843555],
        [0.64360027, 0.5808508 , 0.66146811, 0.21231514, 0.20989774]],

       [[0.62364027, 0.9832091 , 0.60864465, 0.48321069, 0.59538896],
        [0.70015703, 0.95752307, 0.31064099, 0.7214825 , 0.21472639],
        [0.17318232, 0.46258397, 0.25087882, 0.15455238, 0.87378333]]])

In [88]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a) 
print(d)

#They are different because in "c" all observations were equal to 1, so all the observations in "a" were added +1


[[[0.72338693 0.53681583 0.83288232 0.01665714 0.13286795]
  [0.84023085 0.62375665 0.65764074 0.23518552 0.48974744]
  [0.56620855 0.8027896  0.4710776  0.73136086 0.29454315]]

 [[0.01097347 0.08647883 0.94306489 0.00220362 0.68400928]
  [0.04580086 0.35909794 0.66364167 0.249146   0.86858029]
  [0.91020944 0.51424145 0.59611173 0.98075819 0.5231338 ]]]
[[[1.72338693 1.53681583 1.83288232 1.01665714 1.13286795]
  [1.84023085 1.62375665 1.65764074 1.23518552 1.48974744]
  [1.56620855 1.8027896  1.4710776  1.73136086 1.29454315]]

 [[1.01097347 1.08647883 1.94306489 1.00220362 1.68400928]
  [1.04580086 1.35909794 1.66364167 1.249146   1.86858029]
  [1.91020944 1.51424145 1.59611173 1.98075819 1.5231338 ]]]


In [90]:
#12. Multiply a and c. Assign the result to e.
e = a*c
print(e)

[[[0.72338693 0.53681583 0.83288232 0.01665714 0.13286795]
  [0.84023085 0.62375665 0.65764074 0.23518552 0.48974744]
  [0.56620855 0.8027896  0.4710776  0.73136086 0.29454315]]

 [[0.01097347 0.08647883 0.94306489 0.00220362 0.68400928]
  [0.04580086 0.35909794 0.66364167 0.249146   0.86858029]
  [0.91020944 0.51424145 0.59611173 0.98075819 0.5231338 ]]]


In [92]:
#13. Does e equal to a? Why or why not?

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))

In [93]:
f

array([[[0.72338693, 0.53681583, 0.83288232, 0.01665714, 0.13286795],
        [0.84023085, 0.62375665, 0.65764074, 0.23518552, 0.48974744],
        [0.56620855, 0.8027896 , 0.4710776 , 0.73136086, 0.29454315]],

       [[0.01097347, 0.08647883, 0.94306489, 0.00220362, 0.68400928],
        [0.04580086, 0.35909794, 0.66364167, 0.249146  , 0.86858029],
        [0.91020944, 0.51424145, 0.59611173, 0.98075819, 0.5231338 ]]])