In [2]:
import numpy as np 

In [3]:
a=np.random.random((2,3,5))
a

array([[[0.79741997, 0.72909946, 0.64852719, 0.15898131, 0.78011266],
        [0.00859195, 0.40556541, 0.43184119, 0.95489534, 0.90489645],
        [0.82696661, 0.56574368, 0.04332074, 0.07894649, 0.12792425]],

       [[0.71092219, 0.76053281, 0.78561018, 0.86325817, 0.22288229],
        [0.43443219, 0.63576763, 0.17182381, 0.82937577, 0.44754421],
        [0.22634882, 0.92517473, 0.20759534, 0.91683256, 0.81824206]]])

In [4]:
b= np.ones((5,2,3))

In [5]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
a.size


30

In [7]:
b.size

30

In [8]:
c= b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [47]:
d= np.add(a,c)
d

array([[[1.79741997, 1.72909946, 1.64852719, 1.15898131, 1.78011266],
        [1.00859195, 1.40556541, 1.43184119, 1.95489534, 1.90489645],
        [1.82696661, 1.56574368, 1.04332074, 1.07894649, 1.12792425]],

       [[1.71092219, 1.76053281, 1.78561018, 1.86325817, 1.22288229],
        [1.43443219, 1.63576763, 1.17182381, 1.82937577, 1.44754421],
        [1.22634882, 1.92517473, 1.20759534, 1.91683256, 1.81824206]]])

In [10]:
print(a)

[[[0.79741997 0.72909946 0.64852719 0.15898131 0.78011266]
  [0.00859195 0.40556541 0.43184119 0.95489534 0.90489645]
  [0.82696661 0.56574368 0.04332074 0.07894649 0.12792425]]

 [[0.71092219 0.76053281 0.78561018 0.86325817 0.22288229]
  [0.43443219 0.63576763 0.17182381 0.82937577 0.44754421]
  [0.22634882 0.92517473 0.20759534 0.91683256 0.81824206]]]


In [11]:
print(d)

[[[1.79741997 1.72909946 1.64852719 1.15898131 1.78011266]
  [1.00859195 1.40556541 1.43184119 1.95489534 1.90489645]
  [1.82696661 1.56574368 1.04332074 1.07894649 1.12792425]]

 [[1.71092219 1.76053281 1.78561018 1.86325817 1.22288229]
  [1.43443219 1.63576763 1.17182381 1.82937577 1.44754421]
  [1.22634882 1.92517473 1.20759534 1.91683256 1.81824206]]]


In [12]:
e= np.multiply(a,c)
e

array([[[0.79741997, 0.72909946, 0.64852719, 0.15898131, 0.78011266],
        [0.00859195, 0.40556541, 0.43184119, 0.95489534, 0.90489645],
        [0.82696661, 0.56574368, 0.04332074, 0.07894649, 0.12792425]],

       [[0.71092219, 0.76053281, 0.78561018, 0.86325817, 0.22288229],
        [0.43443219, 0.63576763, 0.17182381, 0.82937577, 0.44754421],
        [0.22634882, 0.92517473, 0.20759534, 0.91683256, 0.81824206]]])

In [13]:
#d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max= np.max(d)
d_min= np.min(d)
d_mean=np.mean(d)

In [14]:
d_max

1.9548953410549248

In [15]:
d_min

1.0085919549757278

In [16]:
d_mean

1.5473058478493367

In [31]:
f= np.empty((2,3,5))

In [62]:
for a, valor_a in enumerate(d):
    for b, valor_b in enumerate(valor_a):
        for c, valor in enumerate(valor_b):
            if valor > d_min and valor < d_mean:
                valor = 25
                f[i][b][index] =valor
        
            elif valor > d_mean and valor < d_max:
                valor = 75
                f[a][b][c] = valor
        
            elif valor == d_mean:
                valor = 50
                f[a][b][c] = valor
        
            elif valor == d_min:
                valor = 0
                f[a][b][c] = valor
        
            elif valor == d_max:
                valor = 100
                f[a][b][c] = valor
f

array([[[ 75,  75,  75,  25,  75],
        [  0,  25,  25, 100,  75],
        [ 75,  75,  25,  25,  25]],

       [[ 75,  75,  75,  75,  25],
        [ 25,  75,  25,  75,  25],
        [ 25,  75,  25,  75,  75]]])

In [93]:
g= np.empty(((2,3,5)), dtype = str)

In [94]:
for a, valor_a in enumerate(d):
    for b, valor_b in enumerate(valor_a):
        for c, valor in enumerate(valor_b):
            if valor > d_min and valor < d_mean:
                valor = "B"
                g[a][b][c] =valor
        
            elif valor > d_mean and valor < d_max:
                valor = "D"
                g[a][b][c] = valor
        
            elif valor == d_mean:
                valor = "C"
                g[a][b][c] = valor
        
            elif valor == d_min:
                valor = "A"
                g[a][b][c] = valor
        
            elif valor == d_max:
                valor = "E"
                g[a][b][c] = valor
g

array([[['D', 'D', 'D', 'B', 'D'],
        ['A', 'B', 'B', 'E', 'D'],
        ['D', 'D', 'B', 'B', 'B']],

       [['D', 'D', 'D', 'D', 'B'],
        ['B', 'D', 'B', 'D', 'B'],
        ['B', 'D', 'B', 'D', 'D']]], dtype='<U1')