In [1]:
import numpy as np

In [2]:
a = np.random.random((2,3,5))

In [3]:
a.shape

(2, 3, 5)

In [4]:
b = np.ones((5,2,3),dtype = int)

In [5]:
b.shape

(5, 2, 3)

In [6]:
a.size == b.size

True

In [10]:
c = np.transpose(b)

In [11]:
c.shape

(3, 2, 5)

In [12]:
c = c.reshape(2,3,5)

In [13]:
d = a+c

In [14]:
print("a\n",a,"\n")
print("d\n",d)

a
 [[[0.90589878 0.71397314 0.36259274 0.60192247 0.99723914]
  [0.72420824 0.280621   0.30630123 0.50242262 0.8181086 ]
  [0.79281955 0.69096084 0.38134782 0.25808226 0.45211699]]

 [[0.49162923 0.44437415 0.67593478 0.0126416  0.37036696]
  [0.36644787 0.89746476 0.39763571 0.62760919 0.36004284]
  [0.18530403 0.55623401 0.08212927 0.00580582 0.23289312]]] 

d
 [[[1.90589878 1.71397314 1.36259274 1.60192247 1.99723914]
  [1.72420824 1.280621   1.30630123 1.50242262 1.8181086 ]
  [1.79281955 1.69096084 1.38134782 1.25808226 1.45211699]]

 [[1.49162923 1.44437415 1.67593478 1.0126416  1.37036696]
  [1.36644787 1.89746476 1.39763571 1.62760919 1.36004284]
  [1.18530403 1.55623401 1.08212927 1.00580582 1.23289312]]]


In [15]:
#12. Multiply a and c. Assign the result to e.
e = a * c

In [16]:
e

array([[[0.90589878, 0.71397314, 0.36259274, 0.60192247, 0.99723914],
        [0.72420824, 0.280621  , 0.30630123, 0.50242262, 0.8181086 ],
        [0.79281955, 0.69096084, 0.38134782, 0.25808226, 0.45211699]],

       [[0.49162923, 0.44437415, 0.67593478, 0.0126416 , 0.37036696],
        [0.36644787, 0.89746476, 0.39763571, 0.62760919, 0.36004284],
        [0.18530403, 0.55623401, 0.08212927, 0.00580582, 0.23289312]]])

In [17]:
a

array([[[0.90589878, 0.71397314, 0.36259274, 0.60192247, 0.99723914],
        [0.72420824, 0.280621  , 0.30630123, 0.50242262, 0.8181086 ],
        [0.79281955, 0.69096084, 0.38134782, 0.25808226, 0.45211699]],

       [[0.49162923, 0.44437415, 0.67593478, 0.0126416 , 0.37036696],
        [0.36644787, 0.89746476, 0.39763571, 0.62760919, 0.36004284],
        [0.18530403, 0.55623401, 0.08212927, 0.00580582, 0.23289312]]])

In [18]:
print(f"Does e equal to a? {np.all(e == a)}") 
#the same as sum just that they are multiplying each value

Does e equal to a? True


In [19]:
d_max =  np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [30]:
f = np.empty(d.shape)

In [31]:
f.shape

(2, 3, 5)

In [32]:
print(f)

[[[0.90589878 0.71397314 0.36259274 0.60192247 0.99723914]
  [0.72420824 0.280621   0.30630123 0.50242262 0.8181086 ]
  [0.79281955 0.69096084 0.38134782 0.25808226 0.45211699]]

 [[0.49162923 0.44437415 0.67593478 0.0126416  0.37036696]
  [0.36644787 0.89746476 0.39763571 0.62760919 0.36004284]
  [0.18530403 0.55623401 0.08212927 0.00580582 0.23289312]]]


#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [20]:
print(d_max, d_min, d_mean)

1.9972391449134723 1.005805818186872 1.4831709585958386


In [64]:
for i in range(2):
    for j in range(3):
        for k in range (5):
            value = d[i,j,k]
            if value > d_min and value < d_mean: f[i,j,k] = 25
            elif value > d_mean and value < d_max: f[i,j,k] = 75
            elif value == d_mean: f[i,j,k] = 50
            elif value == d_min: f[i,j,k] = 0
            elif value == d_max: f[i,j,k] = 100
                
print(f)

[[[ 75.  75.  25.  75. 100.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  25.  75.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  75.  25.   0.  25.]]]


#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
        ([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]]

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [60]:
print("d",d,'\n')
print("f",f,'\n')

d [[[1.90589878 1.71397314 1.36259274 1.60192247 1.99723914]
  [1.72420824 1.280621   1.30630123 1.50242262 1.8181086 ]
  [1.79281955 1.69096084 1.38134782 1.25808226 1.45211699]]

 [[1.49162923 1.44437415 1.67593478 1.0126416  1.37036696]
  [1.36644787 1.89746476 1.39763571 1.62760919 1.36004284]
  [1.18530403 1.55623401 1.08212927 1.00580582 1.23289312]]] 

f [[[7.50000000e+01 7.50000000e+01 3.62592739e-01 7.50000000e+01
   1.00000000e+02]
  [7.50000000e+01 2.80620996e-01 3.06301227e-01 7.50000000e+01
   7.50000000e+01]
  [7.50000000e+01 7.50000000e+01 3.81347820e-01 2.58082258e-01
   4.52116989e-01]]

 [[7.50000000e+01 4.44374149e-01 7.50000000e+01 1.26415996e-02
   3.70366963e-01]
  [3.66447871e-01 7.50000000e+01 3.97635711e-01 7.50000000e+01
   3.60042837e-01]
  [1.85304028e-01 7.50000000e+01 8.21292749e-02 0.00000000e+00
   2.32893124e-01]]] 



#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [67]:
f = np.empty(d.shape, dtype = str)

for i in range(2):
    for j in range(3):
        for k in range (5):
            value = d[i,j,k]
            if value > d_min and value < d_mean: f[i,j,k] = 'A'
            elif value > d_mean and value < d_max: f[i,j,k] = 'B'
            elif value == d_mean: f[i,j,k] = 'C'
            elif value == d_min: f[i,j,k] = 'D'
            elif value == d_max: f[i,j,k] = 'E'
                
print(f)

[[['B' 'B' 'A' 'B' 'E']
  ['B' 'A' 'A' 'B' 'B']
  ['B' 'B' 'A' 'A' 'A']]

 [['B' 'A' 'B' 'A' 'A']
  ['A' 'B' 'A' 'B' 'A']
  ['A' 'B' 'A' 'D' 'A']]]
