In [4]:
import numpy as np
a = np.random.random((2,3,5))
print(a)

[[[0.89481417 0.8232678  0.16546425 0.72676872 0.92919774]
  [0.87857597 0.91444131 0.49712057 0.84985716 0.12270634]
  [0.68632607 0.32221623 0.05781639 0.9657331  0.51181919]]

 [[0.7909546  0.83401766 0.56467155 0.73819258 0.14409614]
  [0.83605082 0.04072362 0.36388086 0.00508581 0.31527312]
  [0.65634293 0.35427067 0.12162896 0.42495085 0.5965276 ]]]


In [12]:
b = np.random.randint(1,10, size =(2,3,5))
print(b)

[[[6 2 2 8 3]
  [1 8 8 8 3]
  [9 9 4 5 4]]

 [[2 9 8 6 6]
  [2 4 2 1 7]
  [1 6 2 3 4]]]


In [13]:
c = np.random.rand(2,3,5)
print(c)

[[[0.9381701  0.45795264 0.8553768  0.16675013 0.33085935]
  [0.15225428 0.35500491 0.44672331 0.20295368 0.16106835]
  [0.56921031 0.2468894  0.8497028  0.47971418 0.2428872 ]]

 [[0.25113501 0.86300931 0.43135013 0.57729749 0.49683982]
  [0.31398778 0.09636733 0.15513722 0.03519217 0.47998138]
  [0.96850278 0.518401   0.48907263 0.26242875 0.45937476]]]


In [17]:
#5x2x3

b = np.random.randint(1,2, size =(5,2,3))
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [19]:
c = np.ones((5,2,3))

print(c)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [57]:
print('size',np.size(a))
print('shape',np.shape(a))


size 30
shape (2, 3, 5)


In [58]:
print('size',np.size(b))
print('shape',np.shape(b))


size 30
shape (5, 2, 3)


In [51]:
a = np.random.randint(1,10, size =(2,3,5))
print(a)

b = np.ones([5,2,3])

c = b.reshape(2,3,5)
print(c)

d = a +c
print('matriz a y c , ya tiene la misma estructura de 2,3,5')
print(d)

e = a*c
print(e)

[[[3 2 6 1 8]
  [2 1 2 7 2]
  [5 3 3 7 6]]

 [[8 1 9 2 3]
  [5 5 9 1 1]
  [3 2 9 1 9]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
matriz a y c , ya tiene la misma estructura de 2,3,5
[[[ 4.  3.  7.  2.  9.]
  [ 3.  2.  3.  8.  3.]
  [ 6.  4.  4.  8.  7.]]

 [[ 9.  2. 10.  3.  4.]
  [ 6.  6. 10.  2.  2.]
  [ 4.  3. 10.  2. 10.]]]
[[[3. 2. 6. 1. 8.]
  [2. 1. 2. 7. 2.]
  [5. 3. 3. 7. 6.]]

 [[8. 1. 9. 2. 3.]
  [5. 5. 9. 1. 1.]
  [3. 2. 9. 1. 9.]]]


In [54]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_min)
print(d_max)
print(d_mean)

2.0
10.0
5.2


In [55]:
f = np.empty([2,3,5])
print(f)

[[[3. 2. 6. 1. 8.]
  [2. 1. 2. 7. 2.]
  [5. 3. 3. 7. 6.]]

 [[8. 1. 9. 2. 3.]
  [5. 5. 9. 1. 1.]
  [3. 2. 9. 1. 9.]]]


In [56]:
d

array([[[ 4.,  3.,  7.,  2.,  9.],
        [ 3.,  2.,  3.,  8.,  3.],
        [ 6.,  4.,  4.,  8.,  7.]],

       [[ 9.,  2., 10.,  3.,  4.],
        [ 6.,  6., 10.,  2.,  2.],
        [ 4.,  3., 10.,  2., 10.]]])

In [64]:
for item in d:
    for item2 in item:
        for item3 in item2:
            if item3 > d_min and item3 <d_mean:
                f.append(25)
            else f.append(item3)

SyntaxError: invalid syntax (2791881020.py, line 6)

In [95]:
f = np.where((d_mean > d)&(d > d_min), 25, 
             np.where((d_mean < d)&(d < d_max), 75,
                      np.where(d == d_max, 100,
                              np.where(d == d_mean, 50, 0)
                              )
                     )
            )
print('d_min:\t',d_min)
print('d_max:\t',d_max)
print('d_mean:\t',d_mean)

print('\n',f,'\n\n',d)


d_min:	 2.0
d_max:	 10.0
d_mean:	 5.2

 [[[ 25  25  75   0  75]
  [ 25   0  25  75  25]
  [ 75  25  25  75  75]]

 [[ 75   0 100  25  25]
  [ 75  75 100   0   0]
  [ 25  25 100   0 100]]] 

 [[[ 4.  3.  7.  2.  9.]
  [ 3.  2.  3.  8.  3.]
  [ 6.  4.  4.  8.  7.]]

 [[ 9.  2. 10.  3.  4.]
  [ 6.  6. 10.  2.  2.]
  [ 4.  3. 10.  2. 10.]]]


In [98]:
d1 = ([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

print('D1\n',d1)

f1 = np.empty([2,3,5])
print('F1:\n',f1)

d1_max = np.max(d1)
d1_min = np.min(d1)
d1_mean = np.mean(d1)

print('d_min:\t',d1_min)
print('d_max:\t',d1_max)
print('d_mean:\t',d1_mean)

f1 = np.where((d1_mean > d1)&(d1 > d1_min), 25, 
             np.where((d1_mean < d1)&(d1 < d1_max), 75,
                      np.where(d1 == d1_max, 100,
                              np.where(d1 == d1_mean, 50, 0)
                              )
                     )
            )

print('F1 ESPERADA EJEMPLO:','\n',f1)

D1
 [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918, 1.87078449, 1.7726778, 1.88180042]], [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381], [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881], [1.18068344, 1.9587381, 1.00656599, 1.93402165, 1.73514584]]]
F1:
 [[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
d_min:	 1.00656599
d_max:	 1.97066381
d_mean:	 1.6175069086666667
F1 ESPERADA EJEMPLO: 
 [[[ 75  75  75  25  75]
  [ 75  75  25  25  25]
  [ 75  25  75  75  75]]

 [[ 25  25  25  25 100]
  [ 75  75  75  75  75]
  [ 25  75   0  75  75]]]


In [99]:
print("""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
""")


#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [104]:
f2 = np.empty([2,3,5])

f2 = np.where((d1_mean > d1)&(d1 > d1_min), 'B', 
             np.where((d1_mean < d1)&(d1 < d1_max), 'D',
                      np.where(d1 == d1_max, 'E',
                              np.where(d1 == d1_mean, 'C', 'A')
                              )
                     )
            )
                               
print('PRINT DE EJEMPLO 17 Y 18\n',f2)

PRINT DE EJEMPLO 17 Y 18
 [[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]


In [ ]:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])